/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceSol from "./Governance.sol";
export type { governanceSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MerkleDistributor } from "./MerkleDistributor";
